version: '3'
services:
  pmedicine-api:
    build:
      context: ./pmedicine-api
    ports:
      - "4001:4001"
  pmedicine-front:
    build:
      context: ./pmedicine-front
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_HOST=http://localhost:4001
    depends_on:
      - pmedicine-api